# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f117808fb9eee0b652cdcd87cba8c2bb60ba1f28ac4645769915efc20d70e81b97c018084bcab26de1cb1e2b5fa63888eccafc2da246674a3c1430c7fda20202

test:
  secret_key_base: f9f683b4f9b32a6031ac9eed3a8f983ef13591ac1cbdd0fddfa7e6bd8da3c1ba6aaa8de4a03be0f986624d47acd4c48b41984b8cd82c0bbdee4348a4cc6b7b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
